name: release-binary
on:
    workflow_dispatch:
    push:
      tags:
        - '**'
env:
  PROJECT_NAME: OpenAICompatible

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Binary
        run: bash build.sh

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --no-exec --github-repo ${{ github.repository }}
        env:
          OUTPUT: CHANGELOG.md

      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{env.PROJECT_NAME}}
          path: ./${{env.PROJECT_NAME}}_*

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{env.PROJECT_NAME}}_*
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          body_path: CHANGELOG.md
          generate_release_notes: true
          token: ${{ secrets.TOKEN }}